Repository FIS2425/history-svc, pull requests merged in 2024-12, with the labels that each got.

#46 feat: generate pdf report
  package-lock.json
  package.json
  src/controllers/clinicalHistoryController.js
  src/routes/clinicalHistoryRoutes.js
Labels: 📦 Dependencies, 😎 size/m

#48 feat: Add until date for conditions
  openapi.yaml
  src/controllers/currentConditionController.js
  src/models/CurrentCondition.js
  tests/unit/schemas/clinicalHistorySchema.test.js
Labels: 🧪 Tests, size/s

#51 feat: Implement JWT authentication and authorization middleware
  .env.example
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/api.js
  src/middleware/verifyAuth.js
  src/middleware/verifyToken.js
  src/routes/clinicalHistoryRoutes.js
  tests/unit/controllers/clinicalHistoryController.test.js
  tests/unit/controllers/currentConditionController.test.js
  tests/unit/controllers/treatmentController.test.js
  tests/unit/middleware/dummy
  tests/unit/middleware/verifyTokenAuth.test.js
Labels: ⚙️ Configuration, 🚀 CI/CD, 🧪 Tests, 📦 Dependencies, 😎 size/m

#54 feat: add JWT security to clinical history endpoints in OpenAPI specification
  openapi.yaml
Labels: size/xs

#60 fix: remove uniqueness constraint from file name in schema
  src/models/File.js
Labels: size/xs

#59 feat: update JWT security scheme to use bearer authentication in Open…
  openapi.yaml
Labels: size/xs
