Repository FIS2425/history-svc, pull requests merged in 2025-01, with the labels that each got.

#63 docs: added pdf reports to openapi.yaml
  openapi.yaml
Labels: size/xs

#64 Release version v1.1.0
  .env.example
  .github/workflows/docker-deploy.yml
  .github/workflows/test.yml
  openapi.md
  openapi.yaml
  package-lock.json
  package.json
  src/api.js
  src/controllers/clinicalHistoryController.js
  src/controllers/currentConditionController.js
  src/middleware/verifyAuth.js
  src/middleware/verifyToken.js
  src/models/CurrentCondition.js
  src/models/File.js
  src/routes/clinicalHistoryRoutes.js
  tests/unit/controllers/clinicalHistoryController.test.js
  tests/unit/controllers/currentConditionController.test.js
  tests/unit/controllers/treatmentController.test.js
  tests/unit/middleware/dummy
  tests/unit/middleware/verifyTokenAuth.test.js
  tests/unit/schemas/clinicalHistorySchema.test.js
Labels: 😖 size/l, ⚙️ Configuration, 🚀 CI/CD, 🧪 Tests, 📦 Dependencies

#68 Feature/66 update kubernetes config
  kubernetes/mongodb-deployment.yaml
  kubernetes/mongodb-service.yaml
  package-lock.json
  package.json
  populators/runPopulator.js
Labels: 📦 Dependencies, size/s

#70 feature: add circuit breaker for patient and appointment fetching
  package-lock.json
  package.json
  src/controllers/clinicalHistoryController.js
Labels: 📦 Dependencies, size/s

#73 feature: add environment variables for patient and appointment services in history service deployment
  kubernetes/history-svc-deployment.yaml
Labels: size/s

#72 Release/1.1.1
  .env.example
  kubernetes/history-svc-deployment.yaml
  kubernetes/mongodb-deployment.yaml
  kubernetes/mongodb-service.yaml
  package-lock.json
  package.json
  populators/runPopulator.js
  src/controllers/clinicalHistoryController.js
Labels: ⚙️ Configuration, 📦 Dependencies, 😎 size/m

#77 feature: add Redis caching for patient data and update environment configuration
  .env.example
  docker-compose.yml
  package-lock.json
  package.json
  src/config/redis.js
  src/controllers/clinicalHistoryController.js
Labels: ⚙️ Configuration, 📦 Dependencies, 🐳 Build, size/s

#75 docs: added production server url
  openapi.yaml
Labels: size/xs

#79 feature: add Dragonfly history service and update environment configuration
  .env.example
  kubernetes/dragonfly-history-deployment.yaml
  kubernetes/dragonfly-history-persistentvolumeclaim.yaml
  kubernetes/dragonfly-history-service.yaml
  kubernetes/history-svc-deployment.yaml
  kubernetes/mongo-history-deployment.yaml
  kubernetes/mongo-history-service.yaml
Labels: ⚙️ Configuration, size/s

#83 fix: fixed sample data ids
  populators/ClinicalHistory.js
Labels: size/s

#81 Release/1.2.0
  .env.example
  docker-compose.yml
  kubernetes/dragonfly-history-deployment.yaml
  kubernetes/dragonfly-history-persistentvolumeclaim.yaml
  kubernetes/dragonfly-history-service.yaml
  kubernetes/history-svc-deployment.yaml
  kubernetes/mongo-history-deployment.yaml
  kubernetes/mongo-history-service.yaml
  openapi.md
  openapi.yaml
  package-lock.json
  package.json
  populators/ClinicalHistory.js
  src/config/redis.js
  src/controllers/clinicalHistoryController.js
Labels: ⚙️ Configuration, 📦 Dependencies, 😎 size/m, 🐳 Build

#84 feat: deploy kubernetes workflow first version
  .github/workflows/deploy-kubernetes.yml
Labels: 🚀 CI/CD, size/s

#86 feat: add conditional execution for Kubernetes deployment on successful workflow run and main
  .github/workflows/deploy-kubernetes.yml
Labels: 🚀 CI/CD, size/xs

#88 chore: changed loadbalancer to clusterip
  kubernetes/history-svc-service.yaml
Labels: size/xs

#89 fix: fixed dragonfly secrets and only sending logs once to kafka
  src/api.js
  src/config/logger.js
  src/config/redis.js
  src/models/CurrentCondition.js
  src/utils/kafkaTransport.js
Labels: size/s

#91 feat: implement integration tests for database
  .env.example
  .github/workflows/test.yml
  tests/integration/controllers/dummy
  tests/integration/db.test.js
  tests/integration/middleware/dummy
  tests/integration/routes/dummy
  tests/unit/routes/dummy
  vitest.config.js
Labels: ⚙️ Configuration, 🚀 CI/CD, 🧪 Tests, 😎 size/m

#92 V1.3.0
  .github/workflows/deploy-kubernetes.yml
  kubernetes/history-svc-service.yaml
  src/api.js
  src/config/logger.js
  src/config/redis.js
  src/models/CurrentCondition.js
  src/utils/kafkaTransport.js
Labels: 🚀 CI/CD, 😎 size/m

#94 fix: update Kubernetes deployment workflow to support multiple branch…
  .github/workflows/deploy-kubernetes.yml
Labels: 🚀 CI/CD, size/xs

#93 fix: update Kubernetes deployment workflow to support multiple branches and upgrade checkout action
  .github/workflows/deploy-kubernetes.yml
Labels: 🚀 CI/CD, size/xs

#95 fix: rename service to dragonfly-history in Kubernetes configuration
  kubernetes/dragonfly-history-service.yaml
Labels: size/xs

#98 fix: add error filter to circuit breaker options in getAppointments f…
  src/controllers/clinicalHistoryController.js
Labels: size/xs

#97 fix: add error filter to circuit breaker options in getAppointments function
  .env.example
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/controllers/clinicalHistoryController.js
  tests/integration/controllers/dummy
  tests/integration/db.test.js
  tests/integration/middleware/dummy
  tests/integration/routes/dummy
  tests/unit/routes/dummy
  vitest.config.js
Labels: ⚙️ Configuration, 🚀 CI/CD, 🧪 Tests, 📦 Dependencies, 😎 size/m

#101 docs: update OpenAPI documentation to final version
  openapi.md
Labels: size/xs

#104 feat: add 'Clinical Histories' tag to OpenAPI paths for better organi…
  openapi.yaml
Labels: size/xs

#103 feat: add 'Clinical Histories' tag to OpenAPI paths for better organization
  openapi.yaml
Labels: size/xs
